spring.application.name=orderApp
server.port=8180

rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest

rabbitmq.queues[0].queue=notification.queue
rabbitmq.queues[0].exchange-name=order.exchange
rabbitmq.queues[0].exchange-type=topic
rabbitmq.queues[0].routing-key=order.*
rabbitmq.queues[1].queue=inventory.queue
rabbitmq.queues[1].exchange-name=order.exchange
rabbitmq.queues[1].exchange-type=topic
rabbitmq.queues[1].routing-key=order.created

spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true